baseURL = "https://cslgbk.github.io/"
languageCode = "en-us"
title = "Bodhi Theme"
theme = "bodhi"

[params]
    subtitle = "验证菜鸟"
    avatar = "/t.png"
    author = "Bk"
    commentoSrc = "https://commento.example.com/js/commento.js"
    footerMessage = "Keep it simple."
    disableSearch = false

[[menu.main]]
name = "主页"
url = "/"
weight = 1

[[menu.main_right]]
name = "关于"
url = "/about/"
weight = 1

[[menu.nav]]
name = "博客"
url = "/blog"
weight = 1

[[menu.nav]]
parent = "博客"
name = "tags"
url = "/tags"
weight = 2

[[menu.nav]]
parent = "博客"
name = "categories"
url = "/categories"
weight = 3

[markup.goldmark.renderer]
unsafe= true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    noClasses = false
    tabWidth = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rhnvrm/bodhi"
